# Site settings
title: "CODENAME: Sara"
header-img: img/home-bg.png
email: sara.mpa13@gmail.com
copyright_name: sarastanton
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sarastanton
learn_profile: sarastanton
email_username: sara.mpa13@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
